#!/bin/bash
# Generate TypeScript types from JSON Schema
#
# This script generates Zod schemas and TypeScript types from the
# config.schema.json file, ensuring type safety between backend and frontend.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SCHEMA_PATH="$PROJECT_ROOT/schemas/config.schema.json"
OUTPUT_PATH="$PROJECT_ROOT/web/src/types/generated"

echo "Generating TypeScript types from JSON Schema..."
echo "  Schema: $SCHEMA_PATH"
echo "  Output: $OUTPUT_PATH"

# Create output directory
mkdir -p "$OUTPUT_PATH"

# Generate Zod schema using npx
cd "$PROJECT_ROOT/web"

# Generate the Zod schema
npx json-schema-to-zod -i "../schemas/config.schema.json" -o "src/types/generated/config.zod.ts" -n configSchema --noImport

# Add zod import to the generated schema file
sed -i '' '1s/^/import { z } from "zod";\n\n/' "$OUTPUT_PATH/config.zod.ts"

# Add imports and exports to the generated file
cat > "$OUTPUT_PATH/config.ts" << 'EOF'
/**
 * Generated TypeScript types from config.schema.json
 * DO NOT EDIT - This file is auto-generated by scripts/generate-types.sh
 *
 * To regenerate: make generate-types
 */

import { z } from 'zod';

// Re-export the generated Zod schema
export { configSchema } from './config.zod';

// Import the schema for type inference
import { configSchema } from './config.zod';

// Infer TypeScript types from Zod schema
export type Config = z.infer<typeof configSchema>;

// Validation helper
export function validateConfig(data: unknown): { success: true; data: Config } | { success: false; errors: z.ZodError } {
  const result = configSchema.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, errors: result.error };
}
EOF

echo "✓ TypeScript types generated successfully"
echo ""
echo "Generated files:"
echo "  - $OUTPUT_PATH/config.zod.ts (Zod schema)"
echo "  - $OUTPUT_PATH/config.ts (TypeScript types)"
