#!/bin/sh
set -e

# Reload systemd manager configuration
systemctl daemon-reload

# Enable luminetiq service to start on boot
systemctl enable luminetiq.service

# Start luminetiq service
systemctl start luminetiq.service

exit 0
